
<tables>
    ...

    <table>
        ...
        <name> test1 </name>
        <rules> .List => 
        ListItem($rule(19,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(4096,32,false),@val(61440,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(19,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(18,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(256,32,false),@val(3840,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(18,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(17,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(16,32,false),@val(240,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(17,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(16,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(1,32,false),@val(15,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(16,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(15,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(268435456,32,false),@val(4026531840,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(15,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(14,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(16777216,32,false),@val(251658240,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(14,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(13,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(1048576,32,false),@val(15728640,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(13,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(12,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(65536,32,false),@val(983040,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(12,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(11,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(4096,32,false),@val(61440,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(11,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(10,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(256,32,false),@val(3840,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(10,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(9,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(16,32,false),@val(240,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(9,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(8,
                    $ctr(
                        ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(1,32,false),@val(15,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(8,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(7,
                    $ctr(
                        ListItem($pair(@val(268435456,32,false),@val(4026531840,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(7,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(6,
                    $ctr(
                        ListItem($pair(@val(16777216,32,false),@val(251658240,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(6,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(5,
                    $ctr(
                        ListItem($pair(@val(1048576,32,false),@val(15728640,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(5,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(4,
                    $ctr(
                        ListItem($pair(@val(65536,32,false),@val(983040,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(4,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(3,
                    $ctr(
                        ListItem($pair(@val(4096,32,false),@val(61440,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(3,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(2,
                    $ctr(
                        ListItem($pair(@val(256,32,false),@val(3840,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(2,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(1,
                    $ctr(
                        ListItem($pair(@val(16,32,false),@val(240,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(1,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
        

        ListItem($rule(0,
                    $ctr(
                        ListItem($pair(@val(1,32,false),@val(15,32,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false))) ListItem($pair(@val(0,0,false),@val(0,0,false)))
                    ),
                    @call(
                      String2Id("setb1"),
                      $resolved(
                        ListItem(@val(0,0,false)) ListItem(@val(4,0,false))
                      )
                    )
                 ))
         </rules>
        <default> .K => .K </default>
    </table>
        
</tables>

<in> .List =>
        ListItem($packet("000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000000000000000000000000000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000000000000000000000001000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000000000000000000010001000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000000000000000100010001000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000000000001000100010001000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000000010001000100010001000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000000000000000000001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000000000000000010001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000000000000100010001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000000001000100010001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000000010001000100010001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010000000100010001000100010001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010001000100010001000100010001000100000000000000000000000000000000000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010001000100010001000100010001000100000000000000000000000000000001000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010001000100010001000100010001000100000000000000000000000000010001000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010001000100010001000100010001000100000000000000000000000100010001000000000000000000000000000000000101010101100110",0))
	ListItem($packet("000100010001000100010001000100010001000100010001000100010001000100000000000000000001000100010001000000000000000000000000000000000101010101100110",0))
</in>

syntax Id ::=
    "test1" [token]
